moodlehq/moodle-local_ci

- define_excluded/define_excluded.sh
- remote_branch_checker/remote_branch_checker.sh
While the local_codechecker already had support for the exclusion of thirdpartylibs... CI jobs (define_excluded) was missing it and instead we were using a fixed list.
With these changes (already tested by David @ laptop), all CI jobs will be able to get a better list of excluded stuff, automatically, not requiring changes to the fixed list but getting paths from thirdpartylibs information.
The laptop has been also running the usual CI jobs for the last 5-6 hours with this patch applied, apparently without a problem.
https://tracker.moodle.org/browse/CONTRIB-4696
Ciao :-)
> CONTRIB-4696 Make CI exclusions aware of distributed thirdpartylibs.xml 

- tracker_automations/mv_reopened_out_from_current/mv_reopened_out_from_current.sh
Reopened issues that have failed in the testing phase, already have got
their fixfor versions set. Once they are reopened and moved out from
current integration cycle those fixfor versions, now incorrect, remain
set.
This change just ensures that any issue moved out from integration
(reopened) gets the versions cleaned.
> MDLSITE-3799 ci: reset fixfor versions when moving out from integration.

- tracker_automations/set_integration_priority_to_zero/set_integration_priority_to_zero.sh
This implements #4 of https://tracker.moodle.org/browse/MDLSITE-2892
because it's leading to wrong orders in the integration process.
The rest can wait for some time, but this one is hiting us with
old issues having null altering the expected (0..1) order.
> MDLSITE-2892: Guarantee no null priority lands to integration

- rebase_security/rebase_security.sh
I considered naming this more generically than 'security rebaser' - but in the end I decided to keep the terminology focused on security so its easier to understand.
The script does not attempt to auto-setup the security repository, so the first step to use this is to setup the required branches in the repo to match integration.git (or moodle.git, doesn't really matter):
i.e. for master:
integration/master == security/security-master == security/upstream-ref-maser
From that point on, integrators can start pulling to security-master and it'll start to autorebase.
> MDLSITE-2317 first cut of autorebaser

- tracker_automations/bulk_precheck_issues/criteria/awaiting_integration/query.sh
Before this, only the oned under current integration were
being checked and that was leading, on continuous periods,
where everything happens quickly to some issues never checked.
With this change we'll start to process any issue awaiting integration
that never has been checked before (missing ci label).
> MDLSITE-4018 bulk-checker: process all awaiting integration issues

- remote_branch_checker/remote_branch_checker.sh
- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
This includes 3 commits, all them about https://tracker.moodle.org/browse/MDLSITE-4023:
1) Cleanup of errors.txt output. So all messages will include a level (error, warn, info).
2) Implement gc (normal and aggressive) after a given number of executions (25 and 900 by default). Also, amend the "find" commands so they always, explicitly, exclude .git (and work).
3) When the pre-checker ends with error, look explicitly for controlled "error level" messages. If present, show them. If missing, it's an uncontrolled message and special output is generated, suggesting to the dev to create an issue/contact with integrator.
Ciao :-)
> MDLSITE-4023 - Various fixes

- remote_branch_checker/remote_branch_checker.sh
The problem was the existing rule relied on having subdirectories (i.e.
lib/yui/build/some-random-module/built.js for yui). Where as amd doesn't
have this strcuture so its just lib/amd/build/some-module-min.js). Doing
it this way means a more blanket ignore for yui, but think thats
desierable anyway.
Branch to test this with:
git://github.com/danpoltawski/moodle.git jshinttest
(Test branch Includes 3 commits off master which change yui/amd and normal srv/build direcories)
> MDLSITE-3899 Stop running jshint on built folders

- grunt_process/grunt_process.sh
- prepare_composer_stuff/prepare_composer_stuff.sh
By default, ln itself follows links so, at the end
it's highly possible to get them recursively created
no matter they already exists. To solve this the -n
flag can be used, causing ln not to follow links.
Or, something like that, really I've not thought too
much about it. I just tried the flag and verified it
solved the problem, so applying it everywhere.
Ref: http://www.gossamer-threads.com/lists/linux/kernel/1966
> NOBUG: Avoid weird dereferenced links std behavior.

- remote_branch_checker/lib.php
This will prevent some utilities (sed) breaking badly
against loooong reports leading to "too long line" problems.
Old failure (had to abort it after minutes):
http://integration.moodle.org/job/Precheck%20remote%20branch/16455/
With patch applied, in the laptop, ended in seconds:
http://ci.stronk7.com/view/prehecker/job/Precheck%20remote%20branch/1577/
So it should be ok, ciao :-)
> NOBUG: Format XML output adding linefeeds and indentation

- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
While we recently raised maxcommits to 100 (harcoded in the script),
there are situations where we want to raise the limits more,
specially when we are importing a branch containing years-of-dev
about a new plugin.
In those situations it's interesting to launch the bulk-checker manually
by incrementing the number of allowed commits.
A real example: <https://tracker.moodle.org/browse/MDL-47494>
(there you can see all the "failed" CiBoT attempts and the interest
into being able to, exceptionally, run the checker with more commits
allowed).
> NOBUG: Allow the maxcommits to be configurable

- remote_branch_checker/remote_branch_checker.sh
- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
- tracker_automations/bulk_precheck_issues/criteria/awaiting_integration/override-defaults.sh
- verify_commit_messages/verify_commit_messages.sh
To better support branches with a number of commits, the old, unique,
maxcommits setting is changed plugin-wide to use a couple of settings
instead.
Also, we are moving from an eroor&stop behavior (where the rest of the
checks were not applied) to a error/warn and continue behavior, by
showing the maxcommits warnings and errors within the commits checker.
This may lead to problems is somebody does submit a huge/wrong branch,
but that also was happening right now irrespectively of the # of
commits. If we need countermeasures for that situation, time will tell.
> MDLSITE-4198 ci: split maxcommits into warning(10) and error(100)

- tracker_automations/set_integration_priority_to_one/set_integration_priority_to_one.sh
There are some well known situations:
- issue has "mdlqa" label.
- issue has certain "Must fix for X.Y" version.
Where we must give those issues higher prioring under
continuous integration periods. Till now we do that using
separate filters or custom searches.
Instead, with this job, those issues will be searched periodically
and their "integration priority" will be raised to 1, so they will
appear the first under unmodified pickers.
> MDLSITE-4200 ci: raise integration priority when needed

- verify_commit_messages/verify_commit_messages.sh
1) Clarify the `MDL-1234: foo: case`
2) Throw warning on previously undetected `MDL-1234 - foo: case`
3) Clarify language to say its commit message, not commit, as suggested by @mudrd8mz 
Can be tested with my moodle branch: 
```
git://github.com/danpoltawski/moodle.git MDLSITE-3667-horrible-commits
```
Previously reported errors:
```
------------------------------
commit: f353267, message:
MDL-12345 ok: message is ok
Results:
Ok
------------------------------
commit: 0341e65, message:
MDL-12345-forum: test
Results:
0341e65*error*The commit does not begin with the expected issue code MDL-[0-9]{3,6} and a space.
0341e65*error*The commit does not contain the expected issue code MDL-12345 and a space.
(found 2 problems)
------------------------------
commit: 902a90d, message:
MDL-12345 foo - …
```
> MDLSITE-3667 commits: Improve handling of additional ':' it message

- tracker_automations/bulk_precheck_issues/criteria/awaiting_peer_review/query.sh
If issues are peer reviewed too quickly, they do not get the ci label. 
*note* I haven't tested this yet ;-)
> MDLSITE-3701 tracker: query issues 'peer review in progress' for checks

- tracker_automations/bulk_precheck_issues/util.sh
Using HTTP breaks the HTTPS validation on the tracker. I removed the pom pom girl as it doesn't have an HTTPS equivalent.
Note: Untested.
> Use HTTPS for smileys when possible

- grunt_process/grunt_process.sh
npm install does the same job and respects the shrinkwrap. Thanks to David for reminding me about this when discussing https://tracker.moodle.org/browse/MDL-52250
> Don't use npm update

- detect_conflicts/detect_conflicts.sh
- illegal_whitespace/illegal_whitespace.sh
- tracker_automations/move_to_current_integration/move_to_current_integration.sh
- tracker_automations/mv_reopened_out_from_current/mv_reopened_out_from_current.sh
- tracker_automations/remove_ci_label_from_wip/remove_ci_label_from_wip.sh
This commit cleans all remaining jobs using BUILD_ID and, instead
do use a calculated (now), BUILD_TIMESTAMP, that is what BUILD_ID
used to contain. Note this is basically a cosmetic change to make
scripts to show information as it was some time ago.
Also, in various tracker jobs where a number of issues (with full
details) are returned, to avoid any disclosure of (security...)
information, the file where details are stored is explicitly
deleted at the end of the process.
> MDLSITE-3818 cleanup: kill BUILD_ID and delete issues details

- run_phpunittests/run_phpunittests.sh
This avoid concurrence problems when 2 jobs are trying to issue
create database statements, rare because it's quick command (1s)
but possible (we have experimented it).
> MDLSITE-4358 unit tests: move away from template1 as dflt. database

- check_upgrade_savepoints/check_upgrade_savepoints.php
- check_upgrade_savepoints/check_upgrade_savepoints.sh
Now we pre-process the upgrade code, looking for all strings
within it. If the string is considered dangerous (contains
parenthesis and other chars, then it's replaced by safe placeholder
so next regexp operations won't fail).
Safe strings are kept in place in order to keep code transformations
being as small as possible, in case we want to add more checks in
the future (savepoint params checks...).
> MDLSITE-4366 savepoints: discard unsafe strings to avoid problems

- grunt_process/grunt_process.sh
- remote_branch_checker/checkstyle_converter.php
- remote_branch_checker/lib.php
- remote_branch_checker/remote_branch_checker.sh
Can be tested with, for example of problem output:
```git://github.com/danpoltawski/moodle.git shifter-lint-prob```
And when fixed:
```git://github.com/danpoltawski/moodle.git shifter-lint-ok```
> Check shifter lint errors in the prechecker

- remote_branch_checker/lib.php
When I see the output of a smurf report with php coding style
problems, I frequently mistake it for the phplint check - which is
much more serious problem.
To avoid this confusion I propose to change the shortname to phpcs to
make it clearer.
An example of me dong this was for [this issue](https://tracker.moodle.org/browse/MDL-39913?focusedCommentId=393168&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-393168).
> Change the php code sniffer abbreviation

- remote_branch_checker/checkstyle_converter.php
- remote_branch_checker/lib.php
- remote_branch_checker/remote_branch_checker.sh
- remote_branch_checker/xslt/checkstyle2smurf.xsl
- travis/check_branch_status.php
* Missing setup becomes a warning
* Travis build error becomes an error
* In progress builds just don't count
I added the 'diffurl' field to the checkstyle format so that could pass the url to the build to be linked in smurf.html
> MDLSITE-4414: Precheck for travis status

- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
Just skipping all the Info: lines reported by the prechecker should be enough, only showing the real error ones we are interested to show.
> MDLSITE-4415 CiBoT: exclude info lines from jira report

- prepare_npm_stuff/prepare_npm_stuff.sh
Right now there are a bunch of jobs requiring the
installation of different nodejs stuff with npm.
A) Chain of jobs by branch.
- For branches < 29 (without package.json file):
- The job 'shifter_walk' uses 'shifterbase' to maintain different
shifter versions per branch. (current value ~/shifter_base)
- The job 'less_checker' uses 'recessbase' to maintain different
recess versions per branch. (current value ~/recess_base)
- For branches >= 29 (with package.json file):
- The job 'grunt_process' uses 'npmbase' to maintain different stuff
(grunt, shifter, less, jshint...) per branch. (current value
~npm_base).
B) Prechecker.
- The job 'remote_branch_checker'' uses 'npmbase' to maintain different
stuff (grunt, shifter, less, jshint...) per branch. (current value
~npm_base_prechecker). Run by …
> NOBUG: Centralize all the npm install stuff

- prepare_npm_stuff/prepare_npm_stuff.sh
Using any other (older) version leads to incompatible lessc > 1.4
installed and less files not being processed. So, for the lifes of
27 and 28, we'll be using that 1.1.9 version.
29 and up, not affected, they don't use recess anymore.
> MDLSITE-4419: legacy recess 1.1.9 is the only one for old branches

- tracker_automations/check_marked_as_integrated/util.sh
We have the pre-checker to check for messages in the exact right format,
here we should just search for related commits less striclty
> MDLSITE-2839 relax commit message detector

- grunt_process/grunt_process.sh
- less_checker/less_checker.sh
- prepare_npm_stuff/prepare_npm_stuff.sh
- remote_branch_checker/remote_branch_checker.sh
- shifter_walk/shifter_walk.sh
This makes the jobs needing it:
- shifter_walk for < 29_STABE (chained job)
- less_checker for < 29_STABLE (chained job)
- grunt_process for >= 29_STABLE (both chained job and executed by remote_branch_checker)
- remote_branch_checker 
to execute the new prepare_npm_stuff, instead of handling installation their own.
for < 29_STABLE branches, the stuff is installed into the desired base, but the node_modules link is not created and they are executed from base.
for >= 29_STABLE branches, where there is already a Gruntfile, package.json and npm-shrinkwrap.json, the results are linked to node_modules so everything can be executed from there.
I've tested all executions manually and they seem to be working ok. So I've also deployed this PR in the laptop (by pushing in to the laptop branch). …
> MDLSITE-4419 - Move all jobs to use the new prepare_npm_stuff installer

- grunt_process/grunt_process.sh
I'm slightly confused because i'm sure i've seen this working, but right
now if the grunt command fails it immediately exits without completing
other parts of the script and doens't add an error in the the
grunt-errors.txt. That meant the prechecker didn't detect any failures..
I don't generally like swiddling set -e and set +e, but this was least destructive way
> NOBUG: Detect grunt failures properly

- remote_branch_checker/lib.php
- remote_branch_checker/remote_branch_checker.sh
ESLint superseeds jshint, when MDL-52127 lands we'll have much better JS coding style checking. This adds patch support to the prechecker whilst providing BC with old branches with jshint. 
After we've given this a bit of time to settle I actually would propose we jshint from the prechecker completely, and make ESlint work on older branches instead (we'd still get lint jshint reported by grunt  for amd/yui files). See also MDL-54889.
> MDLSITE-3782 precheck javascript with ESLint when present

- rebase_security/rebase_security.sh
I am sure grunt is supposed to autodetect this, but it doens't seem to be, so avoid those horrible colour escape sequences.
Seen here:
http://integration.moodle.org/job/99.%20SECURITY.%20Rebase%20security%20branch%20(30_STABLE)/549/console
```
[4mRunning "less:bootstrapbase" (less) task[24m
[32m>> [39m2 stylesheets created.
```
> HQ-1070 don't use colors in grunt output

- git_garbage_collector/git_garbage_collector.sh
- rebase_security/rebase_security.sh
- remote_branch_checker/remote_branch_checker.sh
- tracker_automations/check_marked_as_integrated/check_marked_as_integrated.sh
This implements a common git gc cleaner and moves current jobs
needing it (remote_branch_checker and rebase_securty) to use it.
Frequency can be adjusted using gcinterval (defaults to 25) and
gcaggressiveinterval (defaults to 900) if needed.
> HQ-1069 git gc: Apply for common collector in security clones

- prepare_npm_stuff/prepare_npm_stuff.sh
- remote_branch_checker/remote_branch_checker.sh
It seems that in the last move we did put eslint under an
exit-on-error section within the codechecker. That was leading
to executions exiting with error when eslint detected some
coding-style  problem.
Note the fix is not the perfect fix, just a quick attempt to keep
the things working. There are some linked issues where real
improvements should happen:
- MDLSITE-4625, about to properly inspect exit codes an output
for every check and be able to discern correct executions
from incorrect ones.
- MDLSITE-4211, about to have the codechecker, and other local_ci
stuff covered by own unit tests.
> MDLSITE-4644 prechecker: make eslint to run out from exit-on-error

- diff_extract_changes/diff_extract_changes.php
- remote_branch_checker/remote_branch_checker.sh
This PR contains 2 commits,
- the first one just ensures that paths and files containing whitespaces are properly handled. Note that core does not have files with whitespaces, but still because of another issue, it was reproducible when checking a plugin.
- the second one changes the diff processor and now it's able to handle both binary files and files with whitespaces. Previously they were not being detected... and the prechecker was deleting all them. That was not problematic because those binary files are not subject to any analysis, but was inaccurate and, potentially, prone to cracks. Now t just works and all files are processed.
For more details and tests, https://tracker.moodle.org/browse/MDLSITE-3831 is the issue :-)
> MDLSITE-3831 Improve handling of both binary and with-whitespace files

- tracker_automations/check_marked_as_integrated/check_marked_as_integrated.sh
I guess you can test this by taking an issue 'out' of integration temporarily.
At the moment I don't have a way to make this 'green' if it happens and is a false positive, but maybe thats not so bad.
> MDLSITE-4620 detect commits which aren't in 'current integration'

- grunt_process/grunt_process.sh
I actually developed this by added a bats fixture for this on the unit testing branch before developing, have a look:
https://github.com/moodlehq/moodle-local_ci/commit/218e58069983c26d83ce3958ae0cc049927a23cc 
Was a useful exercise writing the tests first, I discovered:
1. You need to do the grunt part before npm symlink is disabled (eliminating my initial attempts to run grunt twice, and eventually realising to just specify both tasks)
2. Need to remember to only run it on 3.2+
But [bats is still crap on travis](https://travis-ci.org/danpoltawski/moodle-local_ci/builds/144131676), so bah for my test driven development experience being ruined!
> MDLSITE-4678 grunt_process: run grunt ignorefiles and detect changes

- detect_conflicts/detect_conflicts.sh
- illegal_whitespace/illegal_whitespace.sh
- phplib/clilib.php
- remote_branch_checker/remote_branch_reporter.php
- tests/01-php_lint.bats
- tests/01-thirdparty_check.bats
- tests/02-checkstyle_manipulations.bats
- tests/02-diff_extract_changes.bats
- tests/02-less_checker.bats
- tests/02-list_valid_components.bats
- tests/02-remote_branch_reporter.bats
- tests/02-travis-branch-checker.bats
- tests/99-detect_conflicts.bats
- tests/99-grunt_process.bats
- tests/99-illegal_whitespace.bats
- tests/99-shifter_walk.bats
- tests/libs/shared_setup.bash
- travis/check_branch_status.php
Update the tests so that they don't run in the directory of the script to prevent a repeat of [MDLSITE-4702](https://tracker.moodle.org/browse/MDLSITE-4702).
Not ready for merging because i haven't converted  `99-detect_conflicts.bats` or `99-illegal_whitespace.bats` yet - because when I did they break! 
I don't love the variable name test `filedir` - suggestiosn welcome
> MDLSITE-4702: Convert tests to neutral path to prevent regression

- tests/00-verifications.bats
- tests/libs/shared_setup.bash
My original implementation of this was to prevent accidents with unset
variables causing an rm -rf /.
But I don't see a neat way to do that..
> NOBUG: Make sure clean_worspace_directory removes .files

- tests/00-verifications.bats
- tests/99-detect_conflicts.bats
- tests/99-illegal_whitespace.bats
- tests/libs/shared_setup.bash
* Centralise the code and add tests
* Don't store it in the cache directory - store it in a tmp directory
which only persists per file/run
* Add helpers for determining when in the first or last test
> NOBUG: Clean up the code for storing $WORKSPACE between tests

- remote_branch_checker/lib.php
- remote_branch_checker/remote_branch_checker.sh
- tests/99-remote_branch_checker.bats
- tests/fixtures/remote_branch_checker/prechecker-fixture-stylelint.xml
Based on top of #120 
Taken the same approach as jshint/eslint (although I think particularly with csslint we should get rid of it soon, its doing so little).
Haven't added tests for the reporting for remote_branch_reporter.php yet
> Utilise stylelint in the prechecker (with tests)

- remote_branch_checker/remote_branch_checker.sh
- tests/99-remote_branch_checker.bats
- tests/fixtures/remote_branch_checker/MDL-55445-master-66e47dd.xml
Fixes a bug which Fred reported - where the css part of report isn't returned when stylelint runs.
I've added a fixture for the branch which I saw this behaviour on
> Ensure stylelint returns a prechecker result, even if not files to check

- compare_databases/compare_databases.php
- compare_databases/compare_databases.sh
- tests/99-compare_databases.bats
As [commented @ MDLSITE-4722](https://tracker.moodle.org/browse/MDLSITE-4722?focusedCommentId=424622&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-424622), I was performing the final tests when I detected that branches < 31_STABLE were failing. The reason is that the ````database_column-info```` internals are different in those old branches.
So this commit just changes the introspection to work differently for 31_STABLE and up ($data protected property) and older branches (individual public properties).
I've already merged this into laptop, after passing local tests, just to be sure it solves the problem. And it seems to be working ok:
- Before (failing): [link](http://ci7.stronk7.com/view/M27/job/25.%20Compare%20databases%20from%2022-23-24-25-26%20(27_STABL …
> MDLSITE-4722 take2 - Make old branches to work

- remote_branch_checker/remote_branch_checker.sh
Prechecker, once has finished the tests requiring complete
codebase, proceeds to delete all the non-patch files. That
includes deleting ignored/excluded files.
Since some hours ago we added node_modules to the list of excluded
and that's leading to its deletion, so obviously nothing from
node_modules is available anymore.
So I just have added an exception to guarantee node_modules persists.
> MDLSITE-4767 regression: avoid prechecker deleting node_modules

- compare_databases/compare_databases.sh
Basically current git status roots the execution.
Looking to those fetches added (recently!) to the database compare
job... i think maybe I added them because of ci tests not ensuring
everything is available in the moodle.git clone (LOCAL_CI_TESTS_GITDIR).
I think I needed it because I was pointing to ongoing integration.git
clone (some tests were dependent of stuff being integrated that week).
I thinkI'm going to, simply, kill the fetches because it's not the job
responsibility to ensure that. travis already does full clone and the
git jobs in jenkins do fetch everything (or can be configured for that f
missing).
> NOBUG: Avoid the job to modify/fetch new stuff

- mustache_lint/mustache_lint.php
- tests/02-mustache_lint.bats
- tests/fixtures/31-mustache_lint-full-html-body.patch
* There was a logic bug (the arguments to strpos the wrong way round!)
* We didn't se tthe content when full body pages were found oops!
> Properly detect 'full html body' templates

- mustache_lint/mustache_lint.php
- mustache_lint/simple_core_component_mustache_loader.php
- tests/02-mustache_lint.bats
- tests/fixtures/31-mustache_lint-theme_loading.patch
We have theme templates, which load partials which override the core partials and thus, we are validating incorrect results. At first I thought we didn't need to care about themes and that it was too complex, but we can work out which theme is wanted from the path of the template.
> MDLSITE-4787 mustache_lint: Handle theme templates better

- tracker_automations/check_marked_as_integrated/check_marked_as_integrated.sh
The previous method of limiting the results returned from the tracker
meant that we would then falsely report about these commits when looking
for unknowned commits.
> NOBUG: filter skip-ci-version-check a better way

- define_excluded/define_excluded.sh
- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
Regression from  b304bc063d3, I used the wrong status. As seen on <a href="https://tracker.moodle.org/browse/MDL-56910?focusedCommentId=438508&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-438508">MDL-56910</a>
> MDLSITE-4798 misreporting about exit status when checks fail

- prepare_composer_stuff/prepare_composer_stuff.sh
It seems that, when we added .lock files to branches (29_STABLE and
up), we forgot about this script performing incorrect updates
instead of install to be sticky to those .lock versions.
> NOBUG: Always use composer install, so .lock versions are observed

- tracker_automations/remove_ci_label_from_waiting_integration/remove_ci_label_from_waiting_integration.sh
When an issue, having the ci label arrives to "waiting for integration"
it's interesting to get the label cleaned, so the prechecker can verify
that everything is correct against current upstream.
This is specially noticeable in continuous-integration periods where
the issues are never moved to "current integration" (monday automated
job) so last prechecker results are really old (happened normally before
peer-review).
This job picks those issues and cleans the label, forcing an extra
prechecker to happen. Has built in machinery to prevent the same issue
to be cleaned too many times (in 1 hour) and other details. Should be
safe to be executed at any time interval.
> MDLSITE-4806 remove the "ci" label when issues arrive to integration

- travis/check_branch_status.php
Just in case it was the cause of
https://integration.moodle.org/job/Precheck%20remote%20branch/29665/
being stuck for 9 hours
> NOBUG: set timeouts for curl request

- remote_branch_checker/checkstyle_converter.php
- tests/02-checkstyle_manipulations.bats
- tests/99-remote_branch_checker.bats
- tests/fixtures/checkstyle/grunt-build-failed.txt
- tests/fixtures/checkstyle/grunt-build-failed.xml
- tests/fixtures/checkstyle/grunt.xml
- tests/fixtures/remote_branch_checker/MDL-53136-master-dc60e4f.xml
- tests/fixtures/remote_branch_checker/fixture-grunt-build-failed.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_oldbranch.xml
- tests/fixtures/remote_branch_checker/prechecker-fixture-stylelint.xml
Previously the prechecker was only reporting on undetected changes in files from grunt. This makes it report on grunt failures.
> MDLSITE-4625 Report grunt errors in the prechecker

- grunt_process/grunt_process.sh
- remote_branch_checker/remote_branch_checker.sh
- tests/1-grunt_process.bats
- tests/2-remote_branch_checker.bats
- tests/fixtures/checkstyle/grunt.txt
- tests/fixtures/checkstyle/grunt.xml
- tests/fixtures/remote_branch_checker/MDL-53136-master-dc60e4f.xml
This is a followup of #158 , where we started to report "ERROR". But there was an "ERROR" that was just the heading for the "GRUNT-CHANGE" problems reported.
This is about to change the ERROR to WARN so it's not reported anymore, because GRUNT-CHANGE are enough and better (detailed).
This also fixes a minor recurrent warning with recent gnu find versions. An of course amends related tests.
Ciao :-)
> MDLSITE-4625 take #2 : Don't show the "heading error", detailed changes are better

- tests/libs/shared_setup.bash
It already has happened twice (see #111) and it's a pain to
realize / detect. Initially I was to going to incorporate this
as a test to setup.bats, but now that the numbering is gone
that test is not executed the first anymore.
So instead, I just clean any trailing slash and forget.
> NOBUG: Avoid slashed LOCAL_CI_TESTS_GITDIR, breaks various tests

- tests/2-remote_branch_checker.bats
The problem is that when we assert the smurf result in the console
output we are just duplicating the assertion which is already happening
by comparing the .xml file. But because we fail before looking at the xml
file we don't get to see how the output differs.. which means in the
case of random travis errors it makes it hard for us to diagnose what
the problem is.
Probably best just to remove that duplciated assertion and hopefully
we'll be able to more easily work out whats going on in case of
failures.
> NOBUG: remove the SMURFRESULT assertion from prechecker tests

- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
- tracker_automations/remove_ci_label_from_waiting_integration/remove_ci_label_from_waiting_integration.sh
With a new optional parameter, informtofiles, where a list of
files can be specified. The job will write one line to each of those
files with format:
MDL-xxxxxxx  unixtime bulk_precheck_issues
Just that, it's the responsibility of other jobs to read and
process that information properly.
> MDLSITE-4808 prechecker: Inform to other jobs about checked issues

- groovyscripts/add_notification_webhook_to_all_jobs.groovy
* Don't notify on the prechecker job (this is expected to fail
and reports to the tracker)
* Always inform about failures on the security rebase and check
mark as integrated jobs
> Notification adjustments

- groovyscripts/remove_post_action_from_all_jobs.groovy
We have used it to automatically delete all the jabber notification
post-build (publishers) in our CI servers. Pretty simple.
> NOBUG: Delete all the specified post-build tasks in a Jenkins server

- remote_branch_checker/remote_branch_checker.sh
We cannot delete the _precheck branches while they run because that
will cause all the /work to be lost before being saved as artifacts.
So, on every run, before performing any other git operation, we check
if we are in a _precheck branch and, if so, proceed to checkout its
base counterpart, checkout it and delete the _precheck branch and
any old stuff it may have.
Note this was introduced because we found some plugins having own
.gitattributes files, playing with auto-crlf settings and causing
next executions of the checker to fail forever. Now, we ensure
nothing is left in the prechecker repo from previous executions.
> NOBUG: Always delete any _precheck branch from previous executions

- remote_branch_checker/remote_branch_checker.sh
- tests/2-remote_branch_checker.bats
Because this comes from tracker fields, we can trim the spaces. Probably
would be more appropiate in the remote branch checker, but its better
covered with tests here and doesn't do any harm.
I decided not to add a testcase for the 'ok with space' case to avoid
wasting the time of a full precheck run.
> MDLSITE-4892 deal with spaces in passed varibles

- grunt_process/grunt_process.sh
- less_checker/less_checker.sh
- prepare_npm_stuff/prepare_npm_stuff.sh
- rebase_security/rebase_security.sh
- remote_branch_checker/remote_branch_checker.sh
- shifter_walk/shifter_walk.sh
- tests/2-remote_branch_checker.bats
- tests/libs/shared_setup.bash
This does:
- make both npmcmd and nodecmd globals optional,
defaulting to "npm" and "node" respectively.
(note there is MDLSITE-4728 about the final
removal but surely we'll need to branch before
that happens and delete other old bits like
shifter/recess)
- better printing the currently used npm/node versions.
- in case grunt-cli needs to be installed explicitly (I've
tried here with node 4, 6, 7 - npm 2, 3, 5 - and it was
installed always), it's done with --no-save, so package
and shrinkwrap files are not modified.
- in prechecker, just moved the mandatory checks before
applying defaults, to be the same than all other scripts.
- move the 2 "cmds" out from tests as far as they are optional.
> MDLSITE-5134 ci: moving to nvm nodejs manager

- check_upgrade_savepoints/check_upgrade_savepoints.php
- tests/1-check_upgrade_savepoints.bats
- tests/fixtures/check_upgrade_savepoints/too_high_savepoint.patch
This checks to make sure that the versions in the upgrade path are not higher than the version defined in the plugin's version.php file.  If this ever happens, it causes a downgrade error.
> Ensure a plugin does not upgrade past its defined version

- check_upgrade_savepoints/check_upgrade_savepoints.php
- tests/1-check_upgrade_savepoints.bats
If a save point is called with the same version, it causes a downgrade error.  This new check looks for duplicate version save point calls throughout the whole upgrade script.
Example of what this catches:
```php
<?php
function xmldb_forum_upgrade($oldversion) {
if ($oldversion < 2014051201) {
upgrade_mod_savepoint(true, 2014051201, 'forum');
}
if ($oldversion < 2014051201) {
upgrade_mod_savepoint(true, 2014051201, 'forum');
}
return true;
}
```
This causes a downgrade error because you cannot call the save point method with the same or lower version.
This error can be "doubled" up due to the second check that counts the number of save points in each if block.  EG:
```php
<?php
function xmldb_forum_upgrade($oldversion) {
if ($oldversion < 2014051201) {
upgrade_mod_savepoint(true, …
```
> Detect multiple calls to save point with same version

- rebase_security/rebase_security.sh
This needs to happen during conflict resolution, not before.
Different dependency versions can exist at different commits.
> MDLSITE-5244 rebase_security: Move prepare_npm_stuff to conflict resolution time

- grunt_process/grunt_process.sh
- remote_branch_checker/remote_branch_checker.sh
- tests/1-grunt_process.bats
Some plugins can come with their own 3rd part libs (thirdpartylibs.xml).
That leads to grunt feeding .eslintignore and .stylelintignore to
make js & css linters to ignore those 3rd part libe.
But those changes, make the grunt check to fail as far as they lead
to change in core detected when the check is being performed for a
non-core plugin. So we just proceed to ignore changes in those files
when it's the case.
> NOBUG: Grunt to ignore changes caused by 3rd part libs

- tests/1-verify_commit_messages.bats
- tests/fixtures/verify_commit_messages/warning-elsewhere.patch
- verify_commit_messages/verify_commit_messages.sh
We don't need the issue code to be followed by space
when searching for it in the message. Only when searching
in the 1st line.
Covered with tests.
Once merged to laptop and master branches... it would be great to force a "cime" on https://tracker.moodle.org/browse/MDL-62610 where the problem was detected with "Part of MDL-62610" being the end of the message (without the trailing space).
Ciao :-)
> Relax searches of issue code elsewhere in the message

- .travis.yml
- remote_branch_checker/lib.php
- remote_branch_checker/xslt/checkstyle2smurf.xsl
- tests/fixtures/remote_branch_checker/fixture-grunt-build-failed.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_manyproblems.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_oldbranch.xml
- tests/fixtures/remote_branch_checker/prechecker-fixture-stylelint.xml
For some reason grunt executions not always lead to the same xml file, some elements become out of expected (fixture) order.
This add a mechanism to enforce a consistent ordering for those checks requiring them (right now, only the grunt ones).
With that, everything should be passing regularly.
> Conditional sorting

- tests/1-verify_commit_messages.bats
- tests/fixtures/verify_commit_messages/amos-bad-syntax.patch
- tests/fixtures/verify_commit_messages/amos-good-commands.patch
- verify_commit_messages/amoslib.php
Components with a digit in the name (such as auth_oauth2) were not
correctly recognised before. This has been fixed upstream in AMOS and
the same fix is being copied over here.
Extending the tests to cover both newly covered cases - valid component
names with a digit, and invalid component name with double underscore.
> MDLSITE-5716 Fix parsing component names in the commit AMOScript

- README.md
And add some basic general links about running php jobs with
different CI/containerised alternatives.
> Remove bogus/outdated link to tracker issue

- .travis.yml
- mustache_lint/mustache_lint.php
- mustache_lint/mustache_lint.sh
- package-lock.json
- package.json
- tests/fixtures/31-mustache_lint-full-html-body.patch
More details:
* https://tracker.moodle.org/browse/MDLSITE-5739
* https://github.com/blackboard-open-source/moodle-plugin-ci/issues/91
As I can see, repo does not include `package-lock.json`, I guess this is intentional, as previously requirement was "^17.3.0" (any compatible version)? I do not use "^18.11.5" as it seems bring up unstable releases above that version when npm is initialised or updated. Perhaps we need to introduce `package-lock.json` to make sure that end user is using the same version which has been integration-tested here?
>  MDLSITE-5739 mustache_lint: error when running on openjdk11

- tracker_automations/bulk_prelaunch_jobs/bulk_prelaunch_jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/postissue.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/query.sh
This job just allows you to perform JQL queries against
a Jira server, launching a number of defined Jenkins jobs for each
issue found and performins some post-actions for each issue.
We are going to use it with a criteria named "awaiting_integration"
so, every user that lands to integration gets some CI jobs executed
for every branch in the issue.
At Jenkins level we'll be throttling those (DEV) jobs to prevent
this script to end using all the available workers.
It's important to make the schedulemins parameter to match the
intervals (in minutes) in the job schedule plan (cron) or some
issues could be processed twice or skipped.
Finally note that the current criteria includes a extra condition:
AND participants not in (tobic)
So we'll be processing an issue only once. This can be …
> Launch predefined jobs against issues returned by a query

- .travis.yml
- tests/1-compare_databases.bats
Not much to say, just move to php72 (required for 3.9dev) and fix associated tests to the new requirements (Moodle >= 3.5...).
Currently broken... this should make travis & bats happy again.
Ciao :-)
> Bump to php72 (new 3.9 requirement) and move dependent tests

- define_excluded/define_excluded.sh
ICS files must have a proper line break so will always fail the illegal whitespace check. Let's just ignore them. They're a false positive.
> Ignore ics files in illegal whitespace checks

- .travis.yml
- prepare_npm_stuff/prepare_npm_stuff.sh
- tests/3-prepare_npm_stuff.bats
This enables all jobs using the script (security rebase, prechecker,
grunt, ... to, automatically use the current node version speficied
in the .nvmrc file.
This includes:
- installing nvm if not available ($HOME/.nvm)
- update nvm to the latest release
- source nvm
- install and use the .nvmrc version
Note that, once working, this renders the use of the nvm-wrapper
jenkins extension futile, as far as it does everything the extension
was doing previously. But better, because now we can control when
our moodle directoy is ready and with the correct .nvmrc file.
This will help to issues like MDL-66109, so whenever a node bump
happens, it's automatically detected and handled by our scripts
that will bump and use the new node version transparently.
> Automatically follow .nvmrc when available

- grunt_process/grunt_process.sh
- less_checker/less_checker.sh
- remote_branch_checker/remote_branch_checker.sh
- shifter_walk/shifter_walk.sh
We need the selected npm and node binaries
available to caller.
This is a followup of #210
> Always source the execution of prepare_npm_stuff

- remote_branch_checker/remote_branch_checker.sh
Old eslint versions, when there weren't any JS file to inspect
just exited silently and without error (exit status = 0).
But since eslint v6.8.0, if there aren't JS files, it exits
with error (exit status = 1). A new option,
--no-error-on-unmatched-pattern, has been created to provide
the BC bahavior.
So we need to discern which eslint is being used. Initally I
did it looking for --version... but it's inexact.
So, surely, the safest way is to verify if the new option exists
or no (using --help). And decide based on that.
That's exactly what this patch does. I've also added a TODO
because one everybody is already using nodejs 14 we won't need
this hack anymore.
Also, added pretty much the same for stylelint, but using the
--allow-empty-input option.
Finally note that there is another …
> Fix change of behavior in eslint/stylelint (exit when no files)

- tracker_automations/continuous_manage_queues/continuous_manage_queues.sh
This script adds some automatisms helping to manage the integration queues:
- candidates queue: issues awaiting from integration not yet in current.
- current queue: issues under current integration.
The automatisms are as follow:
1) Move "important" issues from candidates to current.
2) Keep the current queue fed with issues when it's under a threshold.
The criteria to consider an issue "important" are:
1) It must be in the candidates queue, awating for integration.
2) It must not have the integration_held or security_held labels.
3) It must not have the "agreed_to_be_after_release" text in a comment.
4) At least one of this is true:
a) The issue has a must-fix version.
b) The issue has the mdlqa label.
c) The issue priority is critical or higher.
d) The issue is flagged as security …
> Continuous manage queues (1 of 2)

- tracker_automations/check_marked_as_integrated/check_marked_as_integrated.sh
- tracker_automations/check_marked_as_integrated/util.sh
This is the 1st set of changes providing:
- Support for multiple dev branches (passed as param).
- Support for 3-digit branch names (310, 400...)
- Enforce the fix-for versions rule: "Or stable versions or one dev
version"
TODO:
- Ensure that there aren't missing commits in dev branches, unless the
"yes-only-master" label is present.
- Ensure that the most-immediate version is used when an issue goes
to multiple dev branches.
> Support multiple dev branches and 3-digit branches

- mustache_lint/mustache_lint.php
- tests/1-mustache_lint_plugins.bats
- tests/fixtures/39-mustache_lint_plugins-ignores.patch
- tests/fixtures/39-mustache_lint_plugins-templates.patch
When developing for the Moodle Mobile App, the Mustache templates may
contain Ionic3 / Angular specific syntax that itself is not valid HTML.
The patch adds an option to skip the HTML validation part of the
Mustache linting.
To ignore HTML validation errors, create a file `.mustachelintignore` in
the directory with Mustache templates and define the file name patterns
for the files to be excluded from HTML validation. PHP function
`fnmatch()` is used to search for matches. Lines starting with the hash
sign are considered as comments.
> Add possibility to exclude selected Mustache files from HTML validation

- tests/1-travis-branch-checker.bats
- travis/check_branch_status.php
Part of MDLSITE-6246, this adds support to travis-ci.com
and warns when the "old" (to be stopped Dec 2020) travis-ci.org
is detected for a repo.
Covered with tests.
> Warn about the migration to travis-ci.com when needed

- php_lint/php_lint.sh
- tests/1-php_lint.bats
- tests/fixtures/31-php_lint-vendor.patch
Previously we were excluding vendor directories
but only when "fullmode" (all files) were inspected.
Now this rule also applies to "intercommit" mode (only
files modified between 2 commits).
Covered with tests, checking both 1st level and inner
level vendor directories.
> Ensure that no vendor dir is ever linted

- tracker_automations/bulk_prelaunch_jobs/bulk_prelaunch_jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
Can be used to select which type of job we want to run
(different from all). Useful to sabe some worker slots
when only some job type is failing.
Current aceepted values, apart from "all" are:
- phpunit
- behat-app (it's commented out right now).
- behat-chrome
- behat-goutte
> New optional param (jobtype) added. Defaults to all.

- mustache_lint/js_helper.php
- tests/1-mustache_lint.bats
ESLint searches for plugins relative to the CWD, and is unable to find
plugins when called from outside of the moodleroot, which the plugin
supports.
> Ensure that eslint is called relative to the moodleroot

- check_upgrade_savepoints/check_upgrade_savepoints.php
- tests/1-check_upgrade_savepoints.bats
- tests/fixtures/check_upgrade_savepoints/returning_bool.patch
New xmldb_upgrade_xxxx() functions should start to come
with return (: bool) type hinting. We need to support that.
So I've added a non-capturing and optional group to the regexp matching the
function line and then everything continues working ok. Backed with test.
> Accept return bool type hinting on upgrade functions

- .travis.yml
- tests/1-compare_databases.bats
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
In many situations we want to run all behat tests, keeping phpunit apart
(specially because we run sqlsrv by default for better checking
cross-db).
This issue introduces a new behat-all job type that will behave exactly
that way. Trivial patch.
I've already configured [our jobs](https://ci.moodle.org/view/Tracker/job/TR%20-%20Bulk%20pre-launch%20DEV%20jobs%20(list_of_mdls)/) to show the new options there.
> Add a new jobtype to launch all behat tests (goutte and chrome) together

- tests/1-verify_commit_messages.bats
- tests/fixtures/verify_commit_messages/backslash-ended-lines.patch
- verify_commit_messages/verify_commit_messages.sh
Before the patch, lines ended with backslash (\) were being
interpreted by bash and returned like one unique line,
Now, lines are returned 1 by 1 (ended with backslash) and
verified individually (so their lengths aren't aggregated).
Backed with test, to verify that the lines are handled individually.
> Ensure that the commits verifier split message lines properly

- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/jobs.sh
Mainly because of the new Chrome 89 has come with some surprises, see:
https://tracker.moodle.org/browse/MDL-71108
But also because lately we were getting way less failures with Firefox
than with Chrome, we are switching all ToBiC jobs criteria to run
with Firefox.
> Switch all ToBiC jobs to firefox (failing less right now than Chrome)

- tracker_automations/check_marked_as_integrated/check_marked_as_integrated.sh
Today the first Moodle 4.0 only issue has landed, hence it
has got the first master-only label.
Problem is that such label was not being reset properly in the
loop and once set... it was applied to all subsequent issues.
By moving it to within the loop, we ensure it has the
correct default (empty/false) for every issue (unless
it's detected to be present).
> Reset the ismasteronly flag for every issue being checked

- tests/1-travis-branch-checker.bats
- travis/check_branch_status.php
Most people have moved away from Travis so we should stop warning if
it is not used.
THis change modifies the Travis integration tests to mark the test as
SKIPped if the integration is not setup. A warning is still used if
travis-ci.org is configured but not travis-ci.com.
Note: I have not written a Github Actions integration to replace this yet.
> Stop requiring Travis

- tracker_automations/bulk_prelaunch_jobs/bulk_prelaunch_jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/postissue.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/postissue.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/postissue.sh
Right now, all the comments in the criteria are
harcoded to Integrators.
This change allow you to pick any other role in the project
with blank meaning visible to all.
The jobs @ ci.moodle.org has been already modified to support
this new parameter that will be configurable when any of the
jobs there are executed manually. By default, they continue
restricting to Integrators, until we decide to open them.
Local tests seem to work, but I've not been able to test the Tracker API call itself, so... cross fingers :-)
> Allow to decide the target for the ToBiC comments

- tracker_automations/continuous_manage_queues/continuous_manage_queues.sh
- tracker_automations/normal_manage_queues/lib.sh
- tracker_automations/normal_manage_queues/normal_manage_queues.sh
As discussed, the idea is to use this "normal periods" manager instead of the current "bulk-move on Mondays and bulk-delay on Thursdays (after cutoff)". Basically what we do in the continuous period, when the corresponding queues manager keeps us fed and does also other things (holding...). But the idea is to make issues "flow" instead of the current bulk way commented above.
If we perform this change still will have to:
1. #237 : see how we send the rebase message to issues already in continuous (because now they aren't going to be moved back to candidates).
2. ✔️ Agreed, like in continuous, also in the [integration exposed entries](https://moodle.org/mod/forum/discuss.php?d=422487#p1702271). Agree how we account status (like we do in continuous, queue sizes, basically) and report it.
3. …
> First cut of the normal queues manager

- tracker_automations/send_rebase_message/send_rebase_message.sh
This script will send now 2 different messages:
- Issues under candidate queue, the standard message. It's the one
that existed before under the altcomment, that has been renamed to
altcommentcandidate.
- Issues under current queue, the new standard message, to explain
it will be kept under integration one more week. The standard
message can be overridden by altcommentcurrent.
Filter https://tracker.moodle.org/issues/?filter=22610 has been created (its equivalent in next.tracker is 22700).
> Send rebase message to all issues waiting or in progress

- tracker_automations/count_delayed_last_cycle/count_delayed_last_cycle.sh
- tracker_automations/count_reopened_last_cycle/count_reopened_last_cycle.sh
- tracker_automations/count_test_failed_last_cycle/count_test_failed_last_cycle.sh
From CLDR29 to CLDR33, the month and day names for en_AU were broken, incorrectly
adding a dot (.) after the day and month names. And it was fixed in CLDR34 . So I imagine
that java versions >=9 (when they changed from own locales to CLDR) that are using those CLDR
versions… are doomed (that for sure includes Java10).
Alternatively, there is the following switch:
`-Djava.locale.providers=COMPAT, CLDR`
to make Java own locales to be used instead of CLDR ones.
But as far as en_AU is already fixed in actual versions, we are simply
removing those incorrect dots fom the date fetched with Jira CLI and
done.
Some links:
- https://bugs.openjdk.java.net/browse/JDK-8208487
> Prevent scripts against some buggy JAVA en_AU locales

- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/jobs.sh
Defaulting to STABLE, also TESTING can be used.
Only to the manual "list_of_mdls" jobs (normal and security).
Also, detected some stuff pending in the security one, about
the ability to pick the jobs to execute, so reconciling it
to be feature-paired with the normal one.
> Add support to specify the runner to use

- tracker_automations/set_integration_priority_to_one/set_integration_priority_to_one.sh
Now, all the issues that are blockers (blocks link type) to others and don't have
any unresolved blocking (is blocked by) issue, will get its integration
priority also raised to 1.
Done with pure JiraCLI, to allow it to work against any Jira server (we
won't be able to use some plugin that provides the same in an easier
way).
This has been already executed a number of times and seems to be working
correctly. Like 10-12 issues have got their priority raised. All them
non-blocked blockers.
Note that another follow-up will follow soon, about to lower the
priority of any issue that is blocked.
> Raise priority of non-blocked blocker issues

- tracker_automations/normal_manage_queues/lib.sh
- tracker_automations/normal_manage_queues/normal_manage_queues.sh
- tracker_automations/set_integration_priority_to_one/set_integration_priority_to_one.sh
- tracker_automations/set_integration_priority_to_zero/set_integration_priority_to_zero.sh
This includes 2 commits:
- the first one about to implement in the "change to zero" script the ability to lower the priority for any issue being blocked by unresolved issues.
- the second, about prevent the normal queues manager to perform any change of priority on issues being "blockers" or "blocked", that's something that the set_integration_priority_to_[zero|one] scripts manage in exclusive.
The commit messages do include more details.
Potential TODO: together with changing the integration priority, also add a restricted (to integrators) message from CiBoT explaining why it has been decided to raise or lower the priority (the queues manager already does it, but the set_integration_priority_to_[zero|one] scripts do not. Not really sure if it's needed, so just commenting about it to …
> Lower priority blocked

- remote_branch_checker/checkstyle_converter.php
- remote_branch_checker/lib.php
- remote_branch_checker/remote_branch_checker.sh
- tests/1-upgrade_external_backup.bats
- tests/2-remote_branch_checker.bats
- tests/fixtures/311-upgrade_external_backup-all-ok.patch
- tests/fixtures/311-upgrade_external_backup-all-wrong.patch
- tests/fixtures/311-upgrade_external_backup-backup-ok.patch
- tests/fixtures/311-upgrade_external_backup-external-ok.patch
- tests/fixtures/311-upgrade_external_backup-no-changes.patch
- tests/fixtures/remote_branch_checker/MDL-53572-master-8ce58c9.xml
- tests/fixtures/remote_branch_checker/fixture-bad-amos-commands.xml
- tests/fixtures/remote_branch_checker/fixture-gherkin-lint.xml
- tests/fixtures/remote_branch_checker/fixture-grunt-build-failed.xml
- tests/fixtures/remote_branch_checker/fixture-mustache-lint-js.xml
- tests/fixtures/remote_branch_checker/fixture-mustache-lint.xml
- tests/fixtures/remote_branch_checker/fixture-non-code-update.xml
- tests/fixtures/remote_branch_checker/fixture-thirdparty-css.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_manyproblems.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_oldbranch.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_upgrade_external_backup.xml
- tests/fixtures/remote_branch_checker/prechecker-fixture-stylelint.xml
- upgrade_external_backup_check/upgrade_external_backup_check.sh
New check looking for missing modifications in external/backup when there are new columns added to DB in upgrade.
It happens "often" (here and there) that new columns are added to database in any component and it isn't checked if those new columns require changes in 2 critical areas: backup and external functions.
So, with this new check... when it's detected (in the whole patch being analysed) that there are new columns being added @ any `install.xml` and `upgrade.php` file... and there isn't any change to backup (`/backup/moodle2`) or external (`externallib.php|/external/`) some warnings are added, with text:
```
- WARN: Database modifications (new tables or columns) detected in the patch without any change to some important areas.
- WARN: No changes detected to external functions, that …
```
> New upgrade_external_backup added to CiBoT

- remote_branch_checker/remote_branch_checker.sh
- tests/2-remote_branch_checker.bats
- tests/fixtures/remote_branch_checker/local_ci_fixture_phpcs_aware_components.xml
This is part of https://tracker.moodle.org/browse/MDL-71049
(last step towards having all the machinery working for CiBoT)
Normally, phpcs itself is able to get all the components
installed in a given dir root (it just loads them using
standard core_component class).
But, for performance reasons, with CiBoT, we delete all
files from dir root but those being part of the patchest
being analysed (and a few exceptions like version.php, grunt...).
That means that it's unable to load core_component or find all
the components available in a site.
But that's ok, because one of the first things that the remote
branch checker already does (before deleting files), is to, always,
calculate all the valid components and save them to the
/work/valid_components.txt file.
And then, codechecker can use the …
> Pass the complete list of components to phpcs

- remote_branch_checker/checkstyle_converter.php
- remote_branch_checker/lib.php
- remote_branch_checker/remote_branch_checker.sh
- tests/1-checkstyle_manipulations.bats
- tests/fixtures/checkstyle/travis-error.txt
- tests/fixtures/checkstyle/travis-error.xml
- tests/fixtures/checkstyle/travis.txt
- tests/fixtures/checkstyle/travis.xml
- tests/fixtures/remote_branch_checker/MDL-53572-master-8ce58c9.xml
- tests/fixtures/remote_branch_checker/fixture-bad-amos-commands.xml
- tests/fixtures/remote_branch_checker/fixture-gherkin-lint.xml
- tests/fixtures/remote_branch_checker/fixture-good-amos-commit.xml
- tests/fixtures/remote_branch_checker/fixture-grunt-build-failed.xml
- tests/fixtures/remote_branch_checker/fixture-mustache-lint-js.xml
- tests/fixtures/remote_branch_checker/fixture-mustache-lint.xml
- tests/fixtures/remote_branch_checker/fixture-non-code-update.xml
- tests/fixtures/remote_branch_checker/fixture-thirdparty-css.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_manyproblems.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_oldbranch.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_phpcs_aware_components.xml
- tests/fixtures/remote_branch_checker/local_ci_fixture_upgrade_external_backup.xml
- tests/fixtures/remote_branch_checker/prechecker-fixture-stylelint.xml
- tests/fixtures/remote_branch_reporter/MDL-54987/smurf.html
- tests/fixtures/remote_branch_reporter/MDL-54987/smurf.xml
- tests/fixtures/remote_branch_reporter/MDL-54987/travis.xml
- tests/fixtures/remote_branch_reporter/MDL-55322/smurf.html
- tests/fixtures/remote_branch_reporter/MDL-55322/smurf.xml
- tests/fixtures/remote_branch_reporter/MDL-55322/travis.xml
With everything and everybody already moved to GHA, it
doesn't make much sense to keep the travis checker running
on every CiBoT execution.
Hence, removing it from CiBoT (remote_branch_checker) and
associated tests. But keeping the shell script and its own
tests, in case they are useful for anybody.
Also, added TODO about the possibility of adding a GHA
checker (a simple https request can tell us if actions are
enabled for a repo), but not sure if it's worth it as far
as 99% of people have them enabled.
> Remove the travis checker from CiBoT

- README.md
- composer.json
- initial_jenkins_moodle_setup/initial_jenkins_moodle_setup.sh
- package-lock.json
- remote_branch_checker/remote_branch_checker.sh
- run_phpunittests/run_phpunittests.sh
- version.php
- versions_check_set/versions_check_set.sh
A couple of commits to completely move from local_codechecker to moodle-cs
1. [Remove any mention / use of local_moodlechecker](https://github.com/moodlehq/moodle-local_ci/commit/c1913ef4470b8cc5bc197f1a8a965efd0a195ad7)  …
This isn't going to be any more a dependency of local_ci
because it's being replaced by upstream PHP_CodeSniffer
using the moodle-cs standard installed.
2. [Switch to composer-installed phpcs and moodle-cs](https://github.com/moodlehq/moodle-local_ci/commit/6baac903b7631226d2c4e2c2781012978e182e0e)  …
Not much to say, just install moodle-cs with composer
and ensure that CiBoT is using the phpcs that comes with it.
Let's see how tests go (everything should remain passing 🤞 ).
Ciao :-)
> Move to moodle cs

- phplib/clilib.php
- tests/1-verify_phpunit_xml.bats
- tests/fixtures/verify_phpunit_xml/add_uncovered_test.patch
- tests/fixtures/verify_phpunit_xml/multiple_classes_in_file.patch
- verify_phpunit_xml/create_phpunit_xml.php
- verify_phpunit_xml/verify_phpunit_xml.sh
This light job does the following:
* Creates the phpunit.xml file (without requiring a whole site or database to be installed).
* Validates that all the "tests" directories in code base are covered by some suite in the phpunit.xml file. Errors if not (usually missing subsystem in phpunit.xml.dist file).
* Also reports (without failure) other "abnormal" situations like:
* suite not having any _test.php file.
* _test.php file not having any known unit test class (may require to inform about new parent class to the script).
* _test.php file having multiple known unit tests classes. Warns by default, but can be configured to error too.
And that's all. Planning to add it to the post-checks @ integration.moodle.org, because it's quick and rarely happens (only when some new subsystem arrives). …
> Verify phpunit xml

- tracker_automations/continuous_manage_queues/lib.sh
- tracker_automations/move_to_current_integration/move_to_current_integration.sh
- tracker_automations/normal_manage_queues/lib.sh
All the issues arriving to current integration must have
the "Component Lead Review" field set to no, no matter if
the move is done by any of the queue managers or the bulk-move
that is executed on freeze day.
If they are kept empty / not set, that affects pickers because
one of the sorting criteria is that field.
Technically, all the places that are setting:
customfield_10211:Yes (Currently in integration = Yes)
Must, unconditionally, set:
customfield_15810:No (Component Lead Review = No)
That's exactly what this change does.
> All jobs moving issues to current integration must set clr = no

- remote_branch_checker/remote_branch_checker.sh
- tests/2-remote_branch_checker.bats
- tests/fixtures/remote_branch_checker/local_ci_fixture_upgrade_external_backup_skipped_for_plugins.xml
As far as we don't check the plugins incrementally (commit by commit)
like we do for normal MDL issues by CiBoT or PRs by moodle-plugin-ci,
this check is not useful for checks coming from the plugins database
(because they are just standard moodle branches + 1 unique commit
with all the plugin source code).
So we are disabling this check to be run when the source branches
are PLUGIN-xxx ones (we do the same for the commit check already).
Covered with tests.
PS: Also, delete old TODO comment that should have been deleted
few weeks ago, when another PR was merged.
Note this fixes/closes https://tracker.moodle.org/browse/MDLSITE-6709
> MDLSITE-6709 Avoid running the backup & external check for plugin runs

- mustache_lint/js_helper.php
- tests/1-mustache_lint.bats
- tests/fixtures/31-mustache_lint-js_token_test.patch
From: https://tracker.moodle.org/browse/MDLSITE-6745
> MDLSITE-6745 mustachelint: Ensure that fatal errors include a source

- tracker_automations/manage_waiting_for_feedback/manage_waiting_for_feedback.sh
This controls the flow of issues waiting for feedback (WfF), both
Integration (IR) and Component Leads Review (CLR). Performing
the following actions:
A) Initial notification to all issues sent to WfF, explaining
which the expectations are.
B) After a (configurable) number of days under WfF, reopen the issue
and notify it.
C) Optional. After a (configurable) number of days under WfF,
remind in the issue about the remaining days and expectations.
Note the solution heavily rely on the "Waiting for Feedback Notifications"
field specifically created for this job and also includes workflow
modifications. For more details, visit the issue (MDLSITE-6612).
> MDLSITE-6612 Manage the issues awaiting for feedback

- tests/libs/shared_setup.bash
- tracker_automations/manage_waiting_for_feedback/manage_waiting_for_feedback.sh
We need to use hours instead of days, because the "AFTER -5d" is not accurate enough. In practice it accounts for 4.5 days, or something like that, hence the actions are happening some hours before they should. So, using hours (days * 24) to get more accurate results.
See some of the already processed issues like MDL-66273, MDL-74993 or MDL-75278... it's easy to see there how the reminder notification is happening after 4.5days (aprox), but before the 5 days configured.
Changing to hours will be way more accurate (max error will be just half an hour, not half a day). Note we already use this in other tracker automations, because of the accurateness.
Ciao :-)
> Move from days to hours for timing better resolution

- verify_phpunit_xml/verify_phpunit_xml.sh
In MDL-75716, unit test class names were updated to match file names. As a result the parent class for a couple of tests was changed and must be added to the list of known parent classes.
The old location is not removed as they may still be legitimately used in older versions of Moodle.
> Add renamed classes following MDL-75716

- tracker_automations/bulk_precheck_issues/util.sh
MaxCDN has stopped serving the twemoji images, see:
https://github.com/twitter/twemoji/issues/580
So we are moving to cdnjs.cloudflare.com here so
all those tiny images used by CiBoT (some day we'll converted the majority of them to just Unicode emojis) continue working and making devs to smile a little bit.
This is a test to check that all them are working ok:
> Move away from MaxCDN to CloudFlare CDN

- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
We have been getting some failed builds with database errors on sqlsrv runs, see https://github.com/moodlehq/moodle-php-apache/pull/164#issuecomment-1472883622
This commit changes the ToBiC and awaiting_for_integration runs to use pgsql database temporarily.
> Change to PGSQL temporarily until we fix the recent issues with sqlsrv

- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
No matter of that, the checks still will happen, but it's required to the developer to amend the "Repository" field in the issue.
> Fail the global CiBoT status if unsupported GH git:// URLs are used

- grunt_process/grunt_process.sh
- tests/1-grunt_process.bats
- tests/libs/shared_setup.bash
This includes:
- ignorefiles (that was already being checked, no matter it's called by other tasks).
- jsconfig
- jsdoc
- upgradablelibs
Covered with a real test using Moodle v4.2.0, where jsdoc was failing and nobody noticed.
> Ensure that the grunt job also runs non-default tasks

- package-lock.json
- package.json
We have had reports of valid HTML being rejected because it was not valid at the time of the release of the version of vnu-jar we were using.
The previous version was from 2018.
Bumping to latest - 2023.4.11
> Bump vnu-jar to latest

- tests/fixtures/31-mustache_lint-partials-loaded.patch
The original sample partial core/pix_icon has trailing slash for its <img> tag which gets warned about by the latest version of Nu HTML Validator. Use something else like core/notification_info to avoid this failure.
> Update mustache lint partials loaded sample patch

- tracker_automations/bulk_prelaunch_jobs/bulk_prelaunch_jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_component_lead_review/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/multi_database/jobs.sh
Add a new app (latest-test) job to ToBiC runs:
- Only for master branch, unless the `behat-app` type is specified in jobs supporting it - aka, the manual "list_of_mdls" ones, not the automatic ones.
- Using the agreed tags: `@app&&~@performance&&~@local_behatsnapshots&&~@ci_jenkins_skip`
- Setting the behat timeout to 3 because the app is slow in the browser and may need some extra time here and there.
Everything else are standard job settings. Applied to the 5 job criteria.
> Add a new app (latest-test) job to ToBiC runs

- mustache_lint/mustache_lint.php
- tests/1-mustache_lint.bats
- tests/fixtures/402-mustache_lint-str.patch
So we are:
- replacing the square brackets by parenthesis (allowed in URLs).
- urlenconding the str contents so they are also allowed links.
Backed by tests.
Fixes #270
> Ensure the str helper is url/href compliant

- tracker_automations/continuous_manage_queues/continuous_manage_queues.sh
- tracker_automations/continuous_manage_queues/lib.sh
- tracker_automations/normal_manage_queues/lib.sh
- tracker_automations/normal_manage_queues/normal_manage_queues.sh
This changes the picking order of both the [normal](https://ci.moodle.org/view/Tracker/job/TR%20-%20Manage%20queues%20on%20normal/) and the [continuous](https://ci.moodle.org/view/Tracker/job/TR%20-%20Manage%20queues%20on%20continuous/) queue managers from previous:
- Integration priority.
- Issue priority.
- Number of votes.
- Last update/comment.
To a new:
- Integration priority.
- Issue rank (calculated elsewhere).
Worth noting that, together with the move **we are also disabling a few previous automatisms**:
- Moving "important" issues from the candidates to the current queue. Now we are only moving issues by the new agreed sorting method above.
- Stop raising the integration priority to 1 for issues waiting in the queue for more than X (configurable) days.
Also, worth noting that we …
> MDLSITE-7296 Apply in the queue managers towards using rank

- tracker_automations/continuous_manage_queues/lib.sh
- tracker_automations/normal_manage_queues/lib.sh
In order for the current integration queue to reflect the ordering of issues in the integration backlog, the queues manager will now be moving issues by `Rank` instead of by `Integration priority` and then `Rank`.
It will be up to the product managers to rank all issues regardless of the issues' Integration priority. But it will still be highly encouraged to rank issues with `Integration priority=1` higher whenever possible.
> Move issues to the current queue by Rank

- rebase_security/rebase_security.sh
If both integration.git and security.git, for a given branch, have already the same HEADs, then we don't need to rebase anything, because they are already the same.
The only option to perform is to update the -lastbased branch to point to the same HEAD and forget.
> Don't try any rebase --onto when both repos have matching HEADs

- tracker_automations/continuous_manage_queues/continuous_manage_queues.sh
- tracker_automations/continuous_manage_queues/lib.sh
On continuous we want these "important" issues to be automatically moved to current integration, irrespectively of the "threshold" moves:
- The issue has a must-fix version. [OR]
- The issue has the mdlqa label.
Of course, only issues in the candidates queue, not held and not blocked by others.
Note that we have removed some of the old "important" criteria, namely:
- The issue priority is critical or higher.
- The issue is flagged as security issue.
- The issue belongs to some of these components:
- Privacy
- Automated functional tests (behat)
- Unit tests
See [MDLSITE-7296](https://tracker.moodle.org/browse/MDLSITE-7296) for more info (comments around 29 August 2023).
Tested with [MDL-70371](https://tracker.moodle.org/browse/MDL-70371), seems to be working ok (that issue was a must-fix).
> Enable back (partially) the move from candidates to current

- tracker_automations/bulk_prelaunch_jobs/bulk_prelaunch_jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/multi_database/jobs.sh
By using the new "behat-chrome" jobtype, all the
configurable criteria now will launch chrome DEV jobs.
Note that Firefox continues being the default (more reliable) browser used by all criteria.
> Add support to run just Chrome jobs

- mustache_lint/mustache_lint.php
- tests/1-mustache_lint_plugins.bats
The Mustache lint seems to treat all HTML validation messages as problems, even if they are "info".
I have run into this recently, while checking my course format plugin.  I guess there's been a recent change to the HTML validator that's caused it?  A Mustache file failed validation because some included Moodle Mustache files closed HTML single tags with /> instead of just >.  I got the "info" message "Trailing slash on void elements has no effect and interacts badly with unquoted attribute values."  As far as I can tell, this message is only ever given when there is no actual problem, and if there is an actual problem with a trailing /, I think another, non-info message will likely be given.
I don't think it's necessary to treat "info" messages as problems, and I suspect it will now …
> Treat Mustache "info" message as info, not problem

- tests/1-compare_databases.bats
- tracker_automations/continuous_manage_queues/continuous_manage_queues.sh
- tracker_automations/continuous_manage_queues/lib.sh
Now, all the actions related to holding issues:
- After freeze, any new feature or improvement.
- Last week, any issue type.
- While on-sync, any new feature and improvement.
Are managed both for issues awaiting for IR and awaiting for CLR, so the same outcome (hold issues) happen
exactly the same for both.
Note that we'll have to modify the manual release process slightly to remember to unhold issues from both queues, that will be documented @ https://moodledev.io/general/development/process/release once this is merged and working.
> Make all the "holding" actions to apply both for IR & CLR

- mustache_lint/js_helper.php
- mustache_lint/mustache_lint.php
- tests/1-mustache_lint.bats
Now the JS helper is trimming JS contents
This solves some false positives when the mustache checker is validating (using eslint) all the `{{#js}}...{{/js}}` sections embedded within templates.
Added a new test covering a real case in v4.3.0 of some partial with white space around.
Also we have added a bit of extra information to output so we can assert better in tests if the ESLint check happened or no. Various tests are now looking for that new output.
> Mustache helper now trim JS contents before passing them to ESLint

- git_sync_two_branches/git_sync_two_branches.sh
- git_sync_two_branches/lib.sh
- tests/3-git_sync_two_branches.bats
This job just gets two branches from a given remote (default to origin) and ensures that the target branch is kept 100% on sync with the source one.
It detects if commits have been sent to the target branch by mistake and also, is able to detect rewrites and process them properly in the target branch.
Covered with tests.
> New job to be able to keep two branches on sync

- .github/workflows/ci.yml
Special note about the Bats action, we are moving
to a new one because the actual is not maintained.
amdilabs/setup-bats@v1 ==> brokenpip3/setup-bats-libs@1.5.1
Let's see how it goes...
> GHA is deprecating Node 16 actions, let's bump them

- remote_branch_checker/remote_branch_checker.sh
This is currently setting an empty string when 'integrateto' is set to 'main', causing tools like mdk precheck to fail. E.g. 
https://integration.moodle.org/view/prechecker/job/Precheck%20remote%20branch/148255/console
That job uses MDL-79114-master as the branch name, but 'integrateto' is set to 'main' (see the job params), which results in the job failure. Running a job manually works fine, as long as integrateto is set to master.
> Fixes the generation of displayname when integrateto is set to main

- tests/0-setup.bats
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_component_lead_review/query.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/query.sh
The original query was working wrongly sometimes, because of Jira re-indexing problems. And that was leading to some ToBiC jobs to be relaunched, when they should not.
We have confirmed that, after a re-index, the original query is back to work, but that's not nice-enough outcome.
So we have moved to the already installed JQL Tricks query that seems to be immune to the indexing problems and properly keeps out to all the issues where ToBiC already has participated (by adding a comment).
Note that it has been checked that the JQL Tricks extension is also available for Jira Cloud (with a change in the syntax), but will work there, so it's ok if we add this new use here.
Ref: https://www.j-tricks.com/jql-tricks-cloud-migration.html
> Move from participants to JQL Tricks commentedByUser()

- remote_branch_checker/remote_branch_checker.sh
That sniff covers the core coding style and verifies that all the TODOs (inline or phpdoc block), have a MDL issue associated.
But that's not a requirements for plugins, hence disabling that Sniff for them.
Fixes #289
> Prevent plugin runs to use the moodle.Commenting.TodoComment sniff

- verify_commit_messages/amoslib.php
Since MDL-67063, the format for the plugin type part of the component names in Moodle LMS consists of a letter followed by a combination of letters and numeric characters.
The changes have not been implemented in the legacy_component_name method.
> Accept component names containing numbers

- tests/3-continuous_manage_queues_validation.bats
- tracker_automations/continuous_manage_queues/continuous_manage_queues.sh
- tracker_automations/continuous_manage_queues/lib.sh
> Validate release date on continuous queues manager

- .github/workflows/ci.yml
- tests/1-compare_databases.bats
Only the compare_databases need some tricks because we still have only 4.4.0 tag and 404 and main branches supporting php83. As soon as we have more branches supporting that php version, we'll amend the tests.
> Move tests to use PHP 8.3

- tests/verify_phpunit_xml.bats
- verify_phpunit_xml/create_phpunit_xml.php
Tested locally.
I'm not sure how I can add a test for this in bats because it's only broken by a change in core which requires an autoloaded class in lib/outputcomponents.php. We could switch from 3.11 to main for testing?
> Add autoloader to verify_phpunit_xml

- remote_branch_checker/remote_branch_checker.sh
- tests/fixtures/remote_branch_checker/local_ci_fixture_upgrade_txt_for_404.regex
- tests/fixtures/remote_branch_checker/local_ci_fixture_upgrade_txt_for_405.regex
- tests/remote_branch_checker.bats
This includes both:
- upgrade.txt files, that shouldn't be modified ever.
- UPGRADING.md files, which are 100% managed by mdlrelease.
Note that, if some day we change something in the tool generating the UPGRADING.md files and we apply it as part of an issue, the check will report it as an error, but sure that we can consider that a false positive and proceed to integrate it.
In the other side, 99% of editions won't be legit, hence real positives.
> For 4.5dev and up, let's detect any change to upgrade files

- remote_branch_checker/remote_branch_checker.sh
Before this, we were using the merge commit to name the branches to be pushed. That's useless information because on every merge the commit is different.
Instead, we are going to start using the patch HEAD commit (available in FETCH_HEAD) to name the branches, because that's some information that can be useful if some day we want to start checking what has been already checked and other niceties.
Note that we are forcing to use a short commit length of 16 (to have it homogeneus), no matter that given our moodle.git repo size we are still only needing 11 right now. So any future search will need to be aware of this detail.
> Use the patch HEAD commit to name the branches

- verify_phpunit_xml/create_phpunit_xml.php
MDL-82183 moved all of the output classes to support autoloading and added exceptions to prevent manual inclusion of these files.
> Stop autoloading lib/outputcomponents.php if the classes already exist

- remote_branch_checker/remote_branch_checker.sh
- tests/remote_branch_checker.bats
When we experience merge conflicts in the CiBot Precheck it would be nice to have more information than just: "does not apply clean", e.g. https://integration.moodle.org/job/Precheck%20remote%20branch/160991/artifact/work/errors.txt/*view*/
This adds the output from `git diff --name-only --diff-filter=U`, which provides the list of files not merged because of a conflict.
> Report list of files from merge conflicts

- tracker_automations/bulk_precheck_issues/criteria/awaiting_integration/postissue.sh
- tracker_automations/bulk_precheck_issues/criteria/awaiting_peer_review/postissue.sh
- tracker_automations/bulk_precheck_issues/criteria/developer_request/postissue.sh
- tracker_automations/bulk_prelaunch_jobs/bulk_prelaunch_jobs.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_component_lead_review/postissue.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_component_lead_review/query.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/postissue.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/query.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/postissue.sh
- tracker_automations/bulk_prelaunch_jobs/criteria/multi_database/postissue.sh
* CiBoT results will be posted in the "Pre-check results" field.
* ToBiC results from the `bulk_prelaunch_jobs` will be posted in the "Automated test results" field.
* The positions of the job URL and the job description have been switched.
> Post the CiBoT and ToBiC results in dedicated custom fields in the Tracker (part 2)

- remote_branch_checker/remote_branch_checker.sh
- verify_commit_messages/amoslib.php
Plus, update references of other repositories to point to their respective `main` branch.
- https://github.com/stylelint/stylelint
- https://github.com/moodlehq/moodle-local_amos
> Remove reference to the `master` branch

- tracker_automations/component_leads_integration_mover/lib.sh
The list of available CLRers in the `$available` variable are space-separated. So the internal field separator should be set to space instead of comma.
Plus, there is a minor fix for empty-checking the `$availableCLR`.
To test this fix:
1. Clone the repo.
2. Include `tracker_automations/component_leads_integration_mover/lib.sh`. (We just want to include the `trimstring()` function.)
```bash
source path/to/tracker_automations/component_leads_integration_mover/lib.sh
```
3.  Copy and paste the following script:
```bash
available="amaia tusefomal"
availableProfiles=()
IFS=' ' read -r -a availableCLRs <<<"$available"
for availableCLR in "${availableCLRs[@]}"; do
availableCLR=$(trimstring "$availableCLR")
if [[ -z ${availableCLR} ]]; then
continue
fi
availableProfiles+=("[~${availableCLR}]") …
```
> Use proper field separator for parsing available CLRs

- tests/verify_phpunit_xml.bats
- verify_phpunit_xml/verify_phpunit_xml.sh
Historically we had a blur between `_test` and `_testcase`, but in recent versions we have largely solved this. We now expect:
- every test class name to be suffixed with `_test`
- every test class to be final
- every test class to extend a testcase with class name suffixed `_testcase`
- every testcase class to be abstract
Given these parameters, which have been in place for some time and are checked with phpcs, we can move away from a hardcoded list of accepted testcases, and move towards a regular expression based on the name.
> Accept any _testcase as valid

- remote_branch_checker/remote_branch_checker.sh
When removing files irrelevant to the tests, any files or folders containing the substring "work" remain untouched. This poses a problem if the plugin uses that substring.
See https://tracker.moodle.org/browse/MDLSITE-7849 for more details.
> Acknowledge thirdpartylibs.xml in plugin names with 'work'

- .github/workflows/ci.yml
Ubuntu 24.04 is missing the kcov package. We can switch back to ubuntu-latest, once it points to Ubuntu 26.04
Fixes: #327
> Use Ubuntu 22.04 for code coverage tests

- tracker_automations/component_leads_integration_mover/component_leads_integration_mover.sh
- tracker_automations/continuous_manage_queues/lib.sh
* Update the `Manage queues on continuous job` so that improvements and new features in the CLR queue will not be held during the freeze period until the last week before the release (behaviour A1).
Note: Keeping the behaviour for
- A3b (last week before release, all issues unrelated to the release will be held)
- B1a (during the on-sync period, only bugs will be integrated)
* During the freeze, improvements and new features will be excluded from being triaged for the CLR queue so that they will remain in the candidate queue and be held accordingly.
> Handling of issues for the CLR queue during the code freeze period.

- tracker_automations/continuous_manage_queues/lib.sh
This should prevent issues being integration held if they were simply bumped from CLR back to integration during the freeze. It appears the task is run half hourly, so I set a 2 hour buffer just to cover any cases where it's delayed/doesn't run for some reason.
This is my first contribution to this repo, so please let me know if anything else is required (eg specific testing requirements).
> Avoid holding issues just bumped from CLR to integration

- tracker_automations/continuous_manage_queues/lib.sh
This PR addresses two issues:
- Because security issues are not treated as "important," they are not automatically moved to the current queue. Thus, they get held, especially during the last week before the release, which is incorrect because security issues are considered related to the release. We must again treat security issues in the continuous queues manager as important.
- Must-fix and `mdlqa` issues in CLR are being incorrectly held because the query in `run_A3b` for the CLR part (`filter=23329`) does not exclude must-fix and `mdlqa` issues from being held for issues in the CLR queue.
> Prevent incorrect holds

- list_changed_files/list_changed_files.sh
- mustache_lint/mustache_lint.sh
If files are only renamed, and do not contain any other changes, there is not need to mustache lint them.
This issue has come about because we're renaming all of the mustache templates in MDL-83424 and it's timing out the job.
> Ignore renamed files for mustache lint

- verify_commit_messages/check_amos.php
- verify_commit_messages/verify_commit_messages.sh
This prevent issues when passing a large number of changes files to the amos script.
Previously the git commands were run in the shell script and values passed to the php script, but where there are large numbers of files this breaks because PHP hits ARG limits.
This issue has come about because I'm hitting these limits in MDL-83424
> Allow AMOS to perform git commands

- tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh
Restores the previous lost styling to indicate pass/warn/error details as reported at https://moodle.atlassian.net/browse/ICT-5408
> Separate pre-checker coloured text from link content.

- tracker_automations/bulk_prelaunch_jobs/bulk_prelaunch_jobs.sh
Follows 9f5bc544, and works around current Jira limitation in image hyperlinks and sizing, from original https://github.com/moodlehq/moodle-local_ci/pull/352
> Re-format the job badge/URL display in automated results.

- tracker_automations/component_leads_integration_mover/lib.sh
Jira Cloud does not support mentioning users directly by email address due to privacy and GDPR-related restrictions. Instead, we need to mention users using their accountId.
> Tag CLRs by AccountIDs
