moodlehq/moodle-local_ci

remote_branch_checker/remote_branch_checker.sh

This usually happens only on first run after a major release, where
new branches for patches are available.
Note that for public server I already created the branch manually, to get CiBoT working ASAP. So it won't create anything there.
So I've used the laptop to implement and test this, and seems to be working ok (see the new infos about branch being created):
http://ci.stronk7.com/view/prehecker/job/Precheck%20remote%20branch/1566/console
With this accepted, new future branches MOODLE_30_STABLE.... will be created automatically in the CIs clones.
Ciao :-)

MDLSITE-4044 prechecker: create local branches when valid and needed

---

versions_check_set/versions_check_set.sh

While this does not complete all the checks to be implemented @
MDLSITE-1973, the 2 new tests added:
- Verify that the YYYYMMDD digits are correct, existing date.
- Verify that the YYYYMMDD digits are actual (not future >7d) date.
Do exactly match the 2-3 latest problems we have had lately. So
the earlier we are checking for them, the better.

MDLSITE-1973 versions: Verify wrong and future dates are not allowed

---

tracker_automations/bulk_precheck_issues/util.sh

This reverts commit cf83f2f7ffd51635af6136e83a17d74eeea2d469.
(For anyone not clear, i'm just joking at @FMCorz  :))

Add the best smiley back and enforce use of https

---

grunt_process/grunt_process.sh

This intercepts error output, still passing it to parent process
(usually pre-checker). So the process will now end with error if
there are shifter lint errors found.
I've tested it against:
git://github.com/danpoltawski/moodle.git shifter-lint-prob
and ended with new exit(1): ERROR: Problems running grunt shifter
And also have confirmed that stderr is passed to caller, so the pre-checker will continue being able to detect the problems without modification.

MDLSITE-4329 Make the prechecker exit on shifter lint error too

---

remote_branch_checker/lib.php

(And remove gitorious which has been shut down)

Support HQ gitlab in diff urls

---

travis/check_branch_status.php

MDLSITE-4414 travis: Issue warning when build is canceled

---

tracker_automations/mv_reopened_out_from_current/mv_reopened_out_from_current.sh

- Already tested @ https://tracker.moodle.org/browse/MDL-53820, both with and without mustfix version.
- Amended [Docs](https://docs.moodle.org/dev/index.php?title=Release_process&type=revision&diff=49806&oldid=49645) to keep the parameter updated in CI servers.
- Public server [already contains](http://integration.moodle.org/view/tracker/job/Tracker%20-%20CI%20-%20Move%20reopened%20out%20from%20current/44995/parameters/) the new parameter, ready for an auto-update once/if this is merged.
Ciao :-)

MDLSITE-4017: Prevent mustfix fixfor version to be deleted on reopen

---

rebase_security/rebase_security.sh

Tests in https://gist.github.com/dmonllao/6b9720690d1b23fb5081

HQ-691 security: JS and CSS compilation conflicts autoresolver

---

tracker_automations/check_marked_as_integrated/check_marked_as_integrated.sh

JIRA cli 3.9 and 5.0 seem to return different fixVersion formats,
the regex should be adapted to work with both.
Other changes added as part of this commit:
- Info about skip-ci-version-check label on error messages
- Criteria changed, the issue should be already integrated
- Only the first error was printed

MDLSITE-2839 Expanding regex coverage

---

rebase_security/rebase_security.sh

Previously we were preparing it before we'd cleaned up the branch

HQ-1070 Fix placement of npm preperation

---

rebase_security/rebase_security.sh

Also added a control for infinite loops.

HQ-1070 Abort previous rebases

---

diff_extract_changes/diff_extract_changes.php
remote_branch_checker/remote_branch_checker.sh

Do not integrate yet, being tested with all sort of patchsets.

MDLSITE-3831 Improve handling of both binary and with-whitespace files

---

remote_branch_checker/lib.php
remote_branch_checker/xslt/gargamel.xsl

(Also fixed some docs urls I noticed whilst greping)
We to fix the CSP for this too

MDLSITE-4667 move smurf.html to https friendly stylesheet

---

illegal_whitespace/illegal_whitespace.sh
tests/99-illegal_whitespace.bats
tests/fixtures/31-whitespace-error.patch
tests/libs/shared_setup.bash

I started this fix by first adding tests verifying the current behaviour, then fixing the bug

MDLSITE-4685: fix problems in illegal_whitespace.sh and add tests

---

detect_conflicts/detect_conflicts.sh
tests/00-setup.bats
tests/01-php_lint.bats
tests/01-thirdparty_check.bats
tests/02-less_checker.bats
tests/99-detect_conflicts.bats
tests/99-grunt_process.bats
tests/99-illegal_whitespace.bats
tests/99-shifter_walk.bats
tests/fixtures/31-merge-conflict.patch
tests/libs/shared_setup.bash

- Introduce tests for detect_conflicts
- Fix spaces problem in detect_conflicts
- Add some setup tests for gnu tools in use (can fail when my mac isn't setup right)
- Introduce git_apply_fixture and tidy up tests to avoid having to keep cd'ing

MDLSITE-4685: fix detect_conflicts.sh and improve testing infrastructure

---

phplib/clilib.php
tests/02-travis-branch-checker.bats
travis/check_branch_status.php

* Add bats test for script
* Import clilib from Moodle (will be useful for various other scripts)
* Remove moodle requirement from script

travis/check_branch_status.php: remove moodle depdency

---

check_upgrade_savepoints/savepoints2checkstyle.php
phplib/clilib.php
remote_branch_checker/checkstyle_converter.php
tests/02-checkstyle_manipulations.bats
tests/fixtures/checkstyle/commits.txt
tests/fixtures/checkstyle/commits.xml
tests/fixtures/checkstyle/grunt-errors.txt
tests/fixtures/checkstyle/grunt.txt
tests/fixtures/checkstyle/grunt.xml
tests/fixtures/checkstyle/phplint.txt
tests/fixtures/checkstyle/phplint.xml
tests/fixtures/checkstyle/savepoints.txt
tests/fixtures/checkstyle/savepoints.xml
tests/fixtures/checkstyle/shifter.xml
tests/fixtures/checkstyle/thirdparty.txt
tests/fixtures/checkstyle/thirdparty.xml
tests/fixtures/checkstyle/travis-error.txt
tests/fixtures/checkstyle/travis-error.xml
tests/fixtures/checkstyle/travis.txt
tests/fixtures/checkstyle/travis.xml
verify_commit_messages/commits2checkstyle.php

(Part of the work of stripping things out so that prechecker can be tested)

Add tests for various checkstyle converters (and remove Moodle dependency)

---

tests/02-verify_commit_messages.bats
tests/fixtures/verify_commit_messages/no-code-area.patch
tests/fixtures/verify_commit_messages/no-colon.patch
tests/fixtures/verify_commit_messages/no-issue-id.patch
tests/fixtures/verify_commit_messages/ok.patch
tests/fixtures/verify_commit_messages/too-long-body.patch
tests/fixtures/verify_commit_messages/too-long.patch
verify_commit_messages/verify_commit_messages.sh

I spent a lot longer on this than I wanted to due to stupid bash!

Verify commit messages tests

---

.travis.yml
tests/99-versions_check_set.bats
tests/fixtures/versions_check_set/extra_version_digit.patch
tests/fixtures/versions_check_set/invalid_component.patch
tests/fixtures/versions_check_set/invalid_date.patch
tests/fixtures/versions_check_set/main_version_missing.patch
tests/fixtures/versions_check_set/no_moodle_internal.patch
tests/fixtures/versions_check_set/no_version_defined.patch
tests/fixtures/versions_check_set/short_version.patch
tests/fixtures/versions_check_set/version_too_far_in_future.patch

Not exhasitive! There are a lot of things done by this script, more
tests can be added.
#114 Adds a setup test for GNU style date which is needed for this script to run properly.

Some tests for versions_check_set.sh

---

remote_branch_checker/remote_branch_checker.sh

I think that we are going to need to 'reset' the base at which we merge at - so that we can set the prechecker running _a point in time_.
So these commits are to prepare for that.
Best to review each commit one at a time.

Preparation for prechecker testability

---

remote_branch_checker/remote_branch_checker.sh

Based on #123 - i'm envisaging adding  tests or doing more work on the output..

Simplify output

---

tests/99-remote_branch_checker.bats
tests/fixtures/remote_branch_checker/fixture-non-code-update.xml

The fixture introduced in #126 seems to have unreliable results.. which
caused variable phpcs results in #125 - the failures seemed unrelated
and not part of what was being tested, so simplify that fixture to stop
me going crazy.. (hopefully)

Replace unreliable fixture

---

remote_branch_checker/remote_branch_checker.sh
tests/99-remote_branch_checker.bats
tests/fixtures/remote_branch_checker/fixture-thirdparty-css.xml

Shouldn't be merged until this weeks weekly is published (including MDL-55465)

MDL-55465 Respect .stylelintignore

---

compare_databases/compare_databases.php

The PHP job was really outdated and it was not following the
database_column_info specs properly, leading to both PHP Notices
and innacurate differences output.
This PR just introspects database_column_info via reflection to
get the correct list of properties to compare, moving from old
array/stdclass approach.
Note I've not added yet tests for it, but needed this fixed to be able to change/test the shell script in a reliable way. This change is only php. And differences in results are obvious:
From:
````
Problems found comparing databases!
Parameters: dbhost1=localhost, dbhost2=localhost, dblibrary=native, dbname1=ci_installed_31585_31585, dbname2=ci_upgraded_31585_31585, dbprefix1=cii_, dbprefix2=ciu_, dbtype=mysqli, dbuser1=stronk7, dbuser2=stronk7
Number of errors: 1
Column …
```

MDLSITE-4722 ci: compare_databases php improvements

---

remote_branch_checker/remote_branch_checker.sh
tests/02-verify_commit_messages.bats

It's what we are using in the actual code.

MDLSITE-4704 commit tests: switch to git rev-list

---

tests/02-checkstyle_manipulations.bats
tests/02-verify_commit_messages.bats
tests/99-remote_branch_checker.bats
tests/fixtures/checkstyle/commits-info.txt
tests/fixtures/checkstyle/commits-info.xml
tests/fixtures/remote_branch_checker/fixture-bad-amos-commands.xml
tests/fixtures/remote_branch_checker/fixture-good-amos-commit.xml
tests/fixtures/verify_commit_messages/amos-bad-syntax.patch
tests/fixtures/verify_commit_messages/amos-good-commands.patch
tests/fixtures/verify_commit_messages/amos-incomplete.patch
tests/fixtures/verify_commit_messages/amos-no-modified-files.patch
verify_commit_messages/amoslib.php
verify_commit_messages/check_amos.php
verify_commit_messages/commits2checkstyle.php
verify_commit_messages/verify_commit_messages.sh

Uses code from AMOS (but copy and pasted).

MDLSITE-4440 verify_commits: check amos commands

---

.travis.yml
compare_databases/compare_databases.php
compare_databases/compare_databases.sh
tests/99-compare_databases.bats
tests/libs/shared_setup.bash

List of changes:
- Improved handling of arguments.
- Better git operations preventing dettached heads.
- Added support to check upgrade from multiple origins, keeping BC.
- Support executions without Jenkins.
- Complete output sent to logfile.
- Reduced output includes results.

MDLSITE-4722 Improvements to the database compare shell script

---

grunt_process/grunt_process.sh

MDL-55421 switch from .eslintrc to .stylelintrc for detected whether to run grunt ignorefiles

---

list_valid_components/list_valid_components.php
mustache_lint/mustache_lint.php
mustache_lint/mustache_lint.sh
mustache_lint/simple_core_component_mustache_loader.php
phplib/clilib.php
tests/02-mustache_lint.bats
tests/fixtures/31-mustache_lint-partials-loaded.patch

First commit is the (broken) test which we are going to fix ;-)

MDLSITE-4770 mustache_lint: load partials

---

mustache_lint/mustache_lint.php
tests/02-mustache_lint.bats
tests/fixtures/31-mustache_lint-quote_and_uniq.patch

I know its horrible that i'm re-implmeneting all these helpers.
I am not convinced by all of whats going on in the quote helper, and I commented on MDL-56054 about it. But I could just be misunderstanding and in any case, this linter should do what core does anyway

MDLSITE-4788 mustache_lint: add missing helpers

---

remote_branch_checker/remote_branch_checker.sh
tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh

Creating to allow checks to run, don't merge until tested.

MDLSITE-4798 bulk_prechecker: Reinstate reporting rebase warnings to tracker

---

mustache_lint/js_helper.php
mustache_lint/mustache_lint.php
tests/02-mustache_lint.bats
tests/99-remote_branch_checker.bats
tests/fixtures/31-mustache_lint-js_test.patch
tests/fixtures/remote_branch_checker/fixture-mustache-lint-js.xml

It's not possible to do this easily with grunt because it needs the post-rendered output, but we can fit this in here.

MDLSITE-4790 mustache_lint: Lint JS in templates with eslint

---

tracker_automations/close_tested_issues/close_tested_issues.sh

Look all issues tested and transition them to closed:
- status: closed
- resolution: fixed
- current in integration: empty (no)
- integration date: YYYY-MM-DD (accepting optional date, defaults to today)
- comment: fixed text (acepting optional alternative content)

MDLSITE-4933 ci: job for closing tested issues

---

.gitignore
.travis.yml
mustache_lint/mustache_lint.php
mustache_lint/mustache_lint.sh
mustache_lint/running_validator.txt
package.json
tests/1-mustache_lint.bats
tests/1-verifications.bats

Building on Mark's work in #174 (I would do it on that pull request if I could collaborate on it)

MDLSITE-5003 - switch to using local validator

---

.travis.yml
grunt_process/grunt_process.sh
less_checker/less_checker.sh
mustache_lint/js_helper.php
prepare_npm_stuff/prepare_npm_stuff.sh
rebase_security/rebase_security.sh
remote_branch_checker/remote_branch_checker.sh
shifter_walk/shifter_walk.sh
tests/0-setup.bats
tests/1-grunt_process.bats
tests/1-less_checker.bats
tests/1-php_lint.bats
tests/1-shifter_walk.bats
tests/1-thirdparty_check.bats
tests/2-remote_branch_checker.bats
tests/fixtures/remote_branch_checker/MDL-53136-master-dc60e4f.xml
tests/fixtures/remote_branch_checker/fixture-bad-amos-commands.xml
tests/fixtures/remote_branch_checker/fixture-good-amos-commit.xml
tests/fixtures/remote_branch_checker/local_ci_fixture_oldbranch.xml
tests/libs/shared_setup.bash

Not much to say, look to https://tracker.moodle.org/browse/MDLSITE-5184
This should make things better for next npm "messes". Now stuff is installed on each execution and we are not using own caching of aliased node_modules directories anymore.
There are some tests failing, but they are mustache ones and unrelated with this issue. Will look elsewhere.
Ciao :-)

MDLSITE-5184

---

tracker_automations/progress_automated_tested/progress_automated_tested.sh

Has been working for the last 24 @ laptops:
http://ci7.stronk7.com:81/view/tracker/job/TR%20-%20Progress%20automated%20tests/
(and both transitions worked ok)
The job has been already created @ public server (displaced 30 mins with the laptop one):
https://ci.moodle.org/view/Tracker/job/TR%20-%20Progress%20automated%20tests/
and only needs to be enabled once this is accepted.
Ciao :-)

MDLSITE-5541 cibot waiting2testing and testing2passed transitions

---

.travis.yml
composer.json
tests/0-setup.bats
tests/1-compare_databases.bats

That's the version we are using bundled with local_codechecker and there are some differences in results between both.

MDLSITE-5660 local_ci: Bumpo CiBoT phpcs to 2.7.0

---

composer.json
remote_branch_checker/xslt/checkstyle2smurf.xsl
tests/0-setup.bats

To use https://github.com/moodlehq/moodle-local_codechecker/pull/51
(once it has been merged, not before, of course!) ;-)

Bump to PHPCS 2.9.2

---

tests/1-versions_check_set.bats
tests/fixtures/versions_check_set/short_array_syntax.patch
versions_check_set/versions_check_set.sh

Backed with unit test covering 1 and multiline cases

MDLSITE-5697 local_ci: accept the short array syntax in dependencies

---

tracker_automations/count_delayed_last_cycle/count_delayed_last_cycle.sh

The counter until now was not really accurate because Jira does
not provide a way to search for comments by date.
That was leading to the delayed counter, sometimes, showing some
issues as currently delayed when the messages were old.
With this change, we fetch all the comments from candidate issues
and verify their date corresponds to the last integration cycle.
Only if the delayed messages are current, they are considered.
Also, the final report is improved, showing who, when and how
many times an issue has been delayed:
````
Cycle 13/Sep/19 closed on 2019/09/13 06:35
Started new cycle on 2019/09/13 06:35
MDL-66090, delayed on 2019-09-19 11:39 by sarjona (1 times delayed)
MDL-65668, delayed on 2019-09-19 17:58 by stronk7 (1 times delayed)
MDL-61804, delayed on 2019-09-19 21:09 by …
```

MDLSITE-2892 Now the delayed counter looks for comments by date

---

tracker_automations/delay_awaiting_issues/delay_awaiting_issues.sh

source: https://tracker.moodle.org/browse/MDL-61804

delayed issues automated message. s/will/might :-)

---

tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/jobs.sh
tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/postissue.sh
tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/query.sh

The issues MUST have the code sitting into security-testing prevate
repo.
A new job @ CI will provide a frontend to this.

New criteria able to launch SDEV jobs for requested MDL issues

---

versions_check_set/versions_check_set.sh

This implements:
- Allow 3-digit branches where needed.
- Change some STABLE/master checks to be based on maturity.
- Initial implementation of the "betweenversions" check (to be
able to specify an interval of versions allowed in every branch).
TODO: Complete the "betweenversions" implementation and seek and destroy
all the related TODOs.

Add support for multiple development branches.

---

versions_check_set/versions_check_set.sh

Tested against all branches, it seems that we have a couple of
violations in 35_STABLE and 38_STABLE. Unlikely to cause problems
but glad the tests detected them.
We are going to enable these checks for 39_STABLE and up, using
the following allowed version intervals:
3.5: 20180514-20180517 (grrr there is a 2018061801 version!)
3.7: 20190520
3.8: 20191118 (grrr there is a 2020031700 version!)
3.9: 20200615
3.10: 20200615-20201109
master: 20210525
Will be also modifying the release process to add a point about
keeping the intervals updated when releases happen.

Implement the interval checker to ensure all versions are within limits

---

.travis.yml
composer.json
remote_branch_checker/remote_branch_checker.sh
tests/0-setup.bats

Still not in master, we are moving to phpcs3 to get
some good real runs so people can report problems.
Once the final version is released we'll move back to master.

Bump CiBoT to local_codechecker 3.0.0beta (phpcs3)

---

tracker_automations/manage_waiting_for_feedback/manage_waiting_for_feedback.sh

Because the reminder, sent after 5 days (for example) makes a fake transition (from WfF to WfF) we need to account separately for issues without changes:
- Since sent to WfT  (7 days, for example) for issues that weren't reminded (notification = 2)
- Since remind happened (2 days, for example) for issues that were reminded (notification = 3)

Fix the reopen timing and notification

---

tracker_automations/bulk_precheck_issues/bulk_precheck_issues.sh

Add build time to Bulk pre-check jobs

Add CiBot's build timestamp in the result file

---

tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_component_lead_review/jobs.sh
tracker_automations/bulk_prelaunch_jobs/criteria/awaiting_integration/jobs.sh
tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls/jobs.sh
tracker_automations/bulk_prelaunch_jobs/criteria/list_of_mdls_sdev/jobs.sh
tracker_automations/bulk_prelaunch_jobs/criteria/multi_database/jobs.sh

Reverts moodlehq/moodle-local_ci#335

Revert "Add support for BEHAT_INIT_ARGS parameter"
